### ISSUE TITLE
Add Solr v5 ?

### ISSUE THREAD

**Issue by sckott** [moliware/travis-solr#24]
Thanks for making this :)

Any chance of including v5.x versions ?

I played around on a fork of this repo, and couldn't quite get it to work.

**Comment by luketaverne** [comment]
+1 also interested in a v5.0/ v5.1 of this. Will submit a PR next month if I manage to get it working.

**Comment by lianyi** [comment]
+1

**Comment by moliware** [comment]
I will work on it as soon as possible :)

**Comment by moliware** [comment]
Added :)
I don't work with solr since version 3.X so if something doesn't work as expected please either report it or even better send a pull request :)

Thanks!
